preload.sh

Sometimes after adding space with dd,  btrfs partition could not be expanded because of insufficient space.
A few users had hit this, and a user confirmed the problem went away after he rebooted, which makes me think it is some sort of caching issue.
This is an attempt to fix the issue by disabling free space cache on btrfs. As I have not been able to reproduce this, this is more like a guess at this point.

btrfs no space cache

---

Dockerfile
README.md
preload.sh

Connects to #19
This PR makes the preloader script actually work on newer resinOS versions. Previously it would not work on any resinOS version greater than v1.2 because of a change in the docker on disk format introduced in docker 1.10. 
This PR changes the dind base image to use docker 1.10, and as such will now break preloading on resinOS versions older than v1.2.

19-fix-for-newer-resinos

---

README.md
preload.sh

Connects to #18
So, here goes the second edition of #22 (with @Page-'s comments addressed):
**Changes:**
- Normalised indentation to 4 spaces
- ~~Added `multipath-tools` package, enabling use of `kpathx` to map a partitioned loopdevice (thanks @lurch for the tip)~~
- Moved most parts into (semi-) reusable functions / variables
- Added image OS version detection to switch between storage drivers
- Added filesystem expansion logic for ext4
- Added more comments and log output (which goes to `stderr` to prevent mangling function output)
**To Do:**
<details>
<summary><b>Sample output</b></summary>
<pre><code>
Fetching application data
Using API host https://api.resin.io
Using Registry host registry.resin.io
Using API\_TOKEN
Fetching image data …

Add support for Resin OS 2.0 AUFS storage driver

---

src/preload.sh

Connects to: #31, #30 
Fixes a grave error made in #30; floats aren't supported in these expressions and throw a syntax error.

Fix container size arithmetic (invalid float)

---

src/preload.sh

This fixes an issue where the supervisor (v3.0.1+) won't start up the app without network access.
Connects to: #34

Default apps.json env & config to empty object instead of null

---

src/preload.sh

This enables e2fsck to automatically repair issues that can safely
be fixed without human interaction, allowing the preloader to fail
properly if the file system is corrupted.
Previously e2fsck would print that it needs human interaction and
allow the preloader to continue, causing out-of-disk-space errors
if subsequently, the filesystem could not be expanded.
Connects To: #54

src/preload.sh: Enable auto-repair for e2fsck

---

README.md

This updates the README with usage of the splash screen option,
and adds some pointers to documentation about it.

doc(README): Add splash image usage documentation

---

Dockerfile
README.md
lib/preload.js
package.json
src/preload.py

This requires #65 to be merged first.
Connects to #37 
How it works:
* look at the `deployArtifact` key in the `device-type.json` on the 1st partition of the image. If it contains "-flasher-" continue to the next steps, otherwise preload to the image as before.
* resize the 2nd partition of the outer image (and move the partitions after) so the inner image fits
* resize and preload the inner image (/opt/<deployArtifact stripped of "flasher-"> in the second partition of the outer image)
For resizing the 2nd partition and moving the ones after we use `sfdisk` to generate an sfdisk script of the image layout, update it and create a new image with the updated layout. Then we dd partitions from the original image to the new one, resize the ext filesystem of the 2nd partition and replace the …

Support flasher type images

---

lib/preload.js

Signed-off-by: Alexis Svinartchouk <alexis@resin.io>

Use localhost instead of 0.0.0.0 to connect to Docker on win32

---

.resinci.yml

Signed-off-by: Alexis Svinartchouk <alexis@resin.io>

Rename Dockerfile to avoid the ResinCI/docker/build ci job

---

lib/preload.js

This fixes an issue with loop devices only appearing on the host in some
situations. See https://github.com/balena-io/balena-cli/issues/1008 .

Bind mount host's /dev to container's /dev

---

lib/preload.js
src/preload.py

When the supervisor is < 7.0.0, appData is a list and the python script fails with
```
File "/usr/src/app/preload.py", line 821, in <module>
result = method(**data.get("parameters", {}))
File "/usr/src/app/preload.py", line 766, in main_preload
mountpoint + "/etc/resin-device-pinning.conf"
File "/usr/src/app/preload.py", line 521, in write_resin_device_pinning
if not app_data.get("pinDevice", False):
AttributeError: 'list' object has no attribute 'get'
```
It won't work anyway, so this commit adds a warning when `--pinDevice` is specified for an image that has an old supervisor and ignores `app_data` when it's not a `dict` in `preload.py`.

Don't try to pin releases when supervisor is < 7.0.0

---

Dockerfile

Docker 20.10 supports cgroup v2 and works on Fedora by default.
Changelog-entry: Bump Docker version to 20.10.6
See these posts relating to the support for cgroups v2 in Docker:
- https://www.docker.com/blog/introducing-docker-engine-20-10/
- https://medium.com/nttlabs/cgroup-v2-596d035be4d7
Resolves:
- https://github.com/balena-io/balena-cli/issues/2250
I first reproduced the issue with a Fedora 33 VM.
- installing Docker v19 would not even run `hello-world`
- installing Docker v20 was able to run `hello-world`
- running `balena-preload` would fail to start the Docker-in-Docker container
- bumping the dind version from v17 to v20 allowed Docker-in-Docker to run

Bump Docker version to 20.10.6

---

.editorconfig
.resinci.yml
lib/preload.js
package.json

Instead we can extract the registry URL from the image location
as we do for the manifest and layer endpoints.
Resolves: https://github.com/balena-io-modules/balena-preload/issues/236

Avoid hardcoded registry2 URL

---

src/preload.py

In case the sfdisk command fails we need it to be in a method
that can handle failures, not the container startup cmd.
Connected-to: https://github.com/balena-io/balena-cli/issues/2045

Delay populating global partitions cache until methods call

---

src/preload.py

Update the supervisor repository regex so the supervisor version can be
correctly extracted from the images.
Signed-off-by: Alex Gonzalez <alexg@balena.io>

Fix supervisor repository regex

---

src/preload.py

Starting in balenaOS v2.80.9 the balena.service file was
refactored and the storage-driver is defined by an environment
variable.
Resolves: https://github.com/balena-io-modules/balena-preload/issues/248

Support new storage-driver location in balena.service

---

lib/preload.js

Try to catch errors such as https://github.com/balena-io/balena-cli/issues/2290

Catch errors during build of preload image

---

lib/preload.js

Extends: https://github.com/balena-io-modules/balena-preload/pull/257

Avoid TypeError if build output array is empty

---

Dockerfile
src/preload.py

Support additional platforms like armv7 by building our own DinD image.
- https://jel.ly.fish/f01b4f6c-7116-48b1-abc6-abb5e9b8b4cb (internal)

Use custom dind image based on alpine

---

lib/preload.ts
package.json

Also bumps balena-sdk to v16 (which bumps the node dependency) and TypeScript to v4.5.
Resolves: #269
Change-type: major
See: https://jel.ly.fish/improvement-stop-relying-device-types-v1-device-type-json-unrelated-things-4fbac3c
See: https://jel.ly.fish/brainstorm-topic-cc53b047-fbee-4778-b664-fa7322e9abf4
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

Stop relying on the /device-types/v1 endpoints

---

src/preload.py

Starting in balenaOS `v2.93.0` the supervisor images are tagged
as `balena_supervisor` after being pulled from the balena registry.
See: https://github.com/balena-os/meta-balena/pull/2473
Fixes: https://github.com/balena-io-modules/balena-preload/issues/271

Update supervisor image regex to include tagged images

---

package.json

As node 12 is deprecated and in order to build the CLI on node 14+

minor: build for every major node version >=12

---

lib/preload.ts
package.json

Depends-on: https://github.com/balena-io-modules/balena-request/pull/184
See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/balenaCLI.20bumps/near/450776493

Use the sdk instead of `request` for registry requests

---

lib/preload.ts
package.json

Required for: https://github.com/balena-io/balena-cli/pull/2921
Fibery (for CLI PR): https://balena.fibery.io/Work/Project/Default-API-key-expiry-860

MAJOR: Update `balena-sdk` to v21
