balena-io-modules/balena-preload

- Dockerfile
- README.md
- preload.sh
Added a dockerfile that will be used to deploy this to dockerhub, and also changed the script to work with official docker-in-docker image.
Also updated readme to suggest using the docker  image.
> Deploy as docker image

- preload.sh
> Use X-Docker-Size header for image size calculation

- preload.sh
Pushed to https://hub.docker.com/r/alephan/resin-preload
> Fix rce/docker

- preload.sh
**Changes:**
- lowercase `imageRepo`
- lowercase `imageId`
- split up env vars into `env` and `config` keys
**Example:**
NOTE: `imageRepo` will be omitted from the `apps.json` written to disk.
Before:
```json
[
{
"appId": 123456,
"commit": "xx9fb1xb2xc384cc13c7d2471d2xcfdxx5xxxx4x",
"imageRepo": "camelCase/xx9fb1xb2xc384cc13c7d2471d2xcfdxx5xxxx4x",
"imageId": "registry.resin.io/camelCase/xx9fb1xb2xc384cc13c7d2471d2xcfdxx5xxxx4x",
"env": {
"DEBUG": "*",
"HTTP_PORT": "80",
"HTTPS_PORT": "443",
"RESIN_SUPERVISOR_DELTA": "1",
"RESIN_HOST_LOG_TO_DISPLAY": "0"
}
}
]
```
After:
```json
[
{
"appId": 123456,
"commit": "xx9fb1xb2xc384cc13c7d2471d2xcfdxx5xxxx4x",
"imageRepo": "camelcase/xx9fb1xb2xc384cc13c7d2471d2xcfdxx5xxxx4x",
"imageId": "registry.resin.io/camelcase/xx9fb1xb2xc384cc13c7d2471d2xcfdx …
```
> Fix apps.json format

- preload.sh
Add the missing pipe in `get_app_data()`'s `jq` selector
> Fix missing pipe in get_app_data()

- src/preload.sh
fix for https://github.com/resin-io/resin-preload-image-script/issues/28
> Fix calculation for expanding partition size

- src/preload.sh
Post-#29 container size calculation adjustment to the intended 110%
> Adjust partition expansion size to 110%

- src/preload.sh
Signed-off-by: Pablo Carranza Velez <pablo@resin.io>
> Include app name in the generated apps.json to avoid an unnecessary restart

- src/preload.sh
This uses the registry2 host in the imageId written into the `apps.json`
preventing the supervisor downloading the app again on first boot.
Connects To: #45
> src/preload.sh: Use registry2 in imageId

- src/preload.sh
This makes the preloader use the registry v2 to fix
the supervisor downloading preloaded applications again
on first boot.
Connects-To: #45, #48 
Change-Type: major
> src/preload.sh: Move to registry2

- preload.sh
- src/preload.sh
Add commandline option --splash-image to support changing the boot
splash image.
> Support changing the boot splash image.

- src/preload.sh
This fixes a condition checking for a legacy rce setup,
which would've caused those to not be properly cleaned up.
> src/preload.sh: Fix condition checking for /rce dir

- src/preload.sh
As the uncompressed image layer size cannot be obtained through the docker registry (because the layers' identity encoding is a tarball), and the registry exposes no methods to otherwise do so, we needed to come up with a way to estimate the full container size.
This calculates the container size by fetching each layer blob's last 4 bytes, which are the ISIZE field of the gzip stream, denoting the uncompressed size of the stream, and adds up all layer sizes.
**NOTE:** This method is not reliable for containers with image layers that are 4GB or larger in size, as the gzip ISIZE field is a `uint32`, and the uncompressed size is thus stored as `mod 2^32`, which in turn will result in the size of a 4GB layer being calculated as being zero bytes in size.
Change-Type: minor
Connects To: #54
> src/preload.sh: Estimate container size by reading gzip sizes

- src/preload.sh
This mends some `shellcheck` warnings about double-quoting vars to prevent globbing & word-splitting.
> src/preload.sh: Double-quote vars to prevent globbing / word splitting

- bin/resin-preload
> Make sure --img argument is a file accessible for reading and writing before preloading.

- README.md
> Add a 'Contributing' section to the README.

- README.md
- bin/resin-preload
- lib/preload.js
- src/preload.py
> Allow specifying an app commit to preload.

- README.md
- bin/balena-preload
- lib/preload.js
- package.json
- src/preload.py
Signed-off-by: Alexis Svinartchouk <alexis@resin.io>
Things to do before merging:
* forums.balena.io (referenced in the readme)
* api.balena.io
* registry2.balena.io
* rename organization (links to the docs repo in the README)
* change resin-sdk to balena-sdk in package.json
* change resin-cli-visuals to balena-cli-visuals
> Rename to balena-preload

- lib/preload.js
- src/preload.py
> The splash image is named resin-logo.png

- lib/preload.js
> Don't try to get the device type arch with --dontCheckArch

- lib/preload.js
> Bind mount host's /etc/ssl/certs folder on Linux

- lib/preload.js
> Don't write device name in apps.json

- lib/preload.js
> Filter by commit as part of the query if it's specified

- src/preload.py
Signed-off-by: Gergely Imreh <gergely@balena.io>
> Use more robust regex to extract supervisor semver

- lib/preload.js
> Fetch the app commit if 'latest' is passed

- lib/preload.js
> Fix certificates path in the preloader container

- .gitignore
- lib/preload.js
Signed-off-by: Scott Lowe <scott@balena.io>
> Check os/app architecture compatibility rather than equvalence.

- package.json
> Update to balena-sdk 13.x

- lib/preload.js
- package.json
Change-type: major
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>
> Update to balena-sdk 14.x

- lib/preload.js
- package.json
Connects-to: #221 
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>
> Make the balena-sdk instance an optional parameter

- src/preload.py
> Flake8 on src/preload.py

- lib/preload.js
- src/preload.py
Connects-to: balena-io/balena-cli/issues/1922
> Increase losetup retry delay and count, and print full stderr for dockerd

- lib/preload.js
- package.json
- repo.yml
Update balena-sdk from 14.0.0 to 15.2.1
> Update balena-sdk to 15.x

- lib/bin/balena-preload.js
- tsconfig.json
> Fix build dir paths

- .gitignore
- .npmrc
- lib/preload.js
- src/preload.py
Connects-to: balena-io/balena-cli/issues/1993
> Fix splash image file name for balenaOS >= 2.53.0 (resin → balena)

- lib/preload.js
- package.json
> Better size estimation

- src/preload.py
Connects-to: #233
Spin off PR #234, to simplify that PR and allow the review to focus on other commits.
> Don't truncate error logs

- lib/preload.js
- package.json
> Fix unhandled exception on container.wait()

- lib/preload.js
- src/preload.py
Connects-to: #233 
Connects-to: balena-io/balena-cli/issues/2045
> Enhance comms between CLI process and Python process in container

- package.json
> Update balena-lint to 6.x, typescript to 4.x

- lib/preload.js
> Prefer `this.appId` to `this.application.id`

- lib/bin/balena-preload.js
- lib/preload.js
- package.json
> Switch to tmp-promise instead of tmp

- lib/bin/balena-preload.js
- lib/preload.js
> Make use of async/await to simplify the code

- lib/preload.js
> Use class syntax for declaring instance variables

- lib/preload.js
> Fix missing await

- lib/preload.js
> Start fetching image info sooner and run in parallel with api calls

- lib/preload.ts
Supervisor v13 and above uses the newer v3 target state endpoint. This updates the preloading mechanism so `apps.json` is created using this new format for OS images including this newer supervisor.
> Add support for preloading v3 target state format

- lib/preload.ts
Fix regression with docker 20.10.17
> fix stdin with docker 20.10.17

- lib/preload.ts
Context https://balena.fibery.io/Organisation/Improvement/Use-supervisor-target-state-endpoint-for-preloading-1084?sharing-key=052de598-5c09-4d28-8921-bd11a455287d
> Use SDK getSupervisorTargetStateForApp when getting supervisor state

- package.json
Update balena-sdk from 17.0.0 to 18.0.0
> Update to balena-sdk 18.0.0

- lib/preload.ts
> Fix preload with commit hash

- package.json
> Drop support for Node.js v16

- package.json
Update balena-sdk from 18.0.0 to 19.0.1
> Update balena-sdk to 19.0.1

- package.json
> Update resin-cli-visuals to v2

- package.json
> Remove unused resin-cli-visuals dependency

- lib/preload.ts
- package.json
> Drop bluebird

- package.json
> HOTFIX: Fix balena-sdk major bump

- Dockerfile
Fix: https://github.com/balena-io/balena-cli/issues/2945
> Fix balena-preload pip deps

- lib/preload.ts
- package.json
Update balena-sdk from 21.2.1 to 22.0.0
> Bump balena-sdk to v22.0.0
